HOSTS:
  centos-66-x64:
    roles:
      - agent
      - default
    platform:   el-6-x86_64
    box:        puppetlabs/centos-6.6-64-puppet
    hypervisor: vagrant
    ip:         '10.10.10.81'

CONFIG:
  type: foss
  vagrant_memsize: 2048
  log_level: verbose
